Add zip for revised pBFT consensus
Zilliqa/ZIP pull request #49
Opened 2020-12-10 10:49 UTC by sandipbhoir

2020-12-14 08:29 UTC, bb111189 commented on zips/zip-14.md
> +![new_flow](../assets/zip-14/new_flow.png)
```suggestion
![new_flow](../assets/zip-14/revised_new_flow.png )
```

2020-12-14 08:30 UTC, bb111189 commented on zips/zip-14.md
> +| 14  | Revised pBFT consensus | Draft | Standards Track  | Sandip Bhoir <sandip@zilliqa.com>| 2020-12-10 | 2020-12-10
Let's add George Pîrlea george@zilliqa.com to the ZIP

2020-12-15 06:29 UTC, bb111189 commented on zips/zip-14.md
> +- Round 1 of consensus also called preprep phase will run consensus on microblock/finalblock with txnhashes only.
```suggestion
- Round 1 of consensus also known as the `pre-prepare` phase will run consensus on microblock/finalblock with a set of transaction hashes. This phase is for the committee to agree on the order and set of transactions to process. 
```

2020-12-15 06:30 UTC, bb111189 commented on zips/zip-14.md
> +- Leader starts actual transaction processing after sending out preprep announcement ( mb/fb with txnhashes only).
```suggestion
- Leader starts transaction exeuction after sending out `pre-prepare` announcement ( mb/fb with transaction hashes only).
```

2020-12-15 06:31 UTC, bb111189 commented on zips/zip-14.md
> +- Backups starts actual transaction processing after sending out commit for preprep phase.
```suggestion
- Backups start transaction execution after sending out commit to the leader for `pre-prepare` phase.
```

2020-12-15 06:32 UTC, bb111189 commented on zips/zip-14.md
> +- However, if there is commit failure ( ex. due to missing txns), it will fetch the missing ones from leader and rerun preprep phase (round-1) of consensus.
```suggestion
- However, if there is commit failure ( ex. due to missing txns), the backuip will fetch the missing transactions from leader and rerun the `pre-prepare` phase (round-1) of consensus.
```

2020-12-15 06:33 UTC, bb111189 requested changes
see comments

2021-01-18 10:00 UTC, ansnunez approved these changes

2021-02-11 05:58 UTC, bb111189 approved these changes

2021-02-11 06:01 UTC, merged