P2Pseed transport revamp
Zilliqa/ZIP pull request #52
Opened 2020-12-11 04:20 UTC by chetan-zilliqa

## Description

The ZIP aims to improve network layer communication for seed to seed messaging and also addresses the below issue.
https://github.com/Zilliqa/Issues/issues/650

2020-12-15 07:02 UTC, bb111189 requested changes

2020-12-15 07:02 UTC, bb111189 commented on zips/zip-13.md
> +
```suggestion
```

2020-12-15 07:02 UTC, bb111189 commented on zips/zip-13.md
> +1) Server node will open another port on `33135` and the events for it will be dispatched to the same event loop handling listening events on `33133`.
```suggestion
1) Server node will open another port on `33135` and the events for it will be dispatched to the same event loop handling listening events on port `33133`.
```

2020-12-15 07:02 UTC, bb111189 commented on zips/zip-13.md
> +2) Server node will store the bufferevent for the request in `bufferEventMap`.The key of the map would be key = `IP:PORT`, value = `bufferevent*`
```suggestion
3) Server node will store the bufferevent for the request in `bufferEventMap`. The key of the map would be key = `IP:PORT`, value = `bufferevent*`
```

2020-12-15 07:02 UTC, bb111189 commented on zips/zip-13.md
> +3) For sending the response server node will use `START_BYTE_SEED_TO_SEED_RESPONSE` start byte in `SendMessage()` function call.
```suggestion
4) For sending the response server node will use `START_BYTE_SEED_TO_SEED_RESPONSE` start byte in `SendMessage()` function call.
```

2020-12-15 07:02 UTC, bb111189 commented on zips/zip-13.md
> +4) In case server does not send any response for incoming request, server node will just remove the bufferevent from bufferEventMap.Termination of socket connection will only be done by events from c
```suggestion
4) In case server does not send any response for incoming request, the server node will just remove the bufferevent from bufferEventMap. Termination of socket connection will only be done by events from client side.
```

2020-12-15 07:02 UTC, bb111189 commented on zips/zip-13.md
> +5) Buffer event cleanup will only be done by events from client side(socket closure,socket error).
```suggestion
6) Buffer event cleanup will only be done by events from client side (socket closure and socket error).
```

2021-01-13 08:34 UTC, ansnunez approved these changes

2021-01-20 03:03 UTC, sandipbhoir approved these changes

2021-03-10 05:47 UTC, ansnunez approved these changes

2021-03-10 05:51 UTC, sandipbhoir approved these changes

2021-03-11 09:41 UTC, merged