zip16_merkle-proof
Zilliqa/ZIP pull request #56
Opened 2021-01-06 08:14 UTC by kaikawaliu

2021-01-06 08:28 UTC, bb111189 commented on zips/zip-16.md
> +With Merkle Tree we are allowed to verify all the account state data in Zilliqa. But in order to verify accounts offline, we need a feature to provide proof which is important for the security of Lay
```suggestion
With Merkle Tree we are allowed to verify all the account state data in Zilliqa. But in order to verify accounts offline, we need a feature to provide proof which is important for the security of Layer 2 services and cross-chain bridges
```

2021-01-06 08:30 UTC, bb111189 commented on zips/zip-16.md
> +This ZIP introduces Merkle Proof which allows us to verify each data entry stored in Merkle Tree, including account status, contract states and so on. But currently, the standard RPC api does not pro
```suggestion
This ZIP introduces Merkle Proof which allows us to verify each data entry stored in Merkle Tree, including account status, contract states and so on. But currently, the standard RPC api does not provide an access to these proofs. This ZIP suggest an additional RPC method at the seed node to provide Merkle Proof for account and contract states.
```

2021-01-06 08:34 UTC, bb111189 commented on zips/zip-16.md
> +Verification is important for trustless decentralised protocol. While verifying upon full state is not always possible since the storage could be huge for some light weight usage. With Merkle Proof,
```suggestion
Verification is important for trustless decentralised protocol. Verifying the full state may not always possible since the storage cost could be huge for some light weight usage such as light client. With Merkle Proof, a user 
```

2021-01-06 08:36 UTC, bb111189 commented on zips/zip-16.md
> +As above, only interested state entries are provided in result after parsing. If the user want to dump the proof for all the state entries of a contractr, an empty array should be provided in the req
```suggestion
As above, only interested state entries are provided in result after parsing. If the user want to dump the proof for all the state entries of a contract, an empty array should be provided in the request.
```

2021-01-06 08:36 UTC, bb111189 requested changes
See suggestion

2022-02-04 02:02 UTC, renlulu approved these changes

2022-02-04 03:53 UTC, bb111189 requested changes

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +This ZIP introduces Merkle Proof which allows us to verify each data entry stored in Merkle Tree, including account status, contract states and so on. But currently, the standard RPC api does not pro
```suggestion
This ZIP introduces Merkle Proof which allows us to verify each data entry stored in Merkle Patricia Tree, including account status, contract states and so on. But currently, the standard RPC API does not provide access to these proofs. This ZIP suggests an additional RPC method at the seed node to provide Merkle Proof for account and contract states.
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +Verification is important for trustless decentralised protocol. Verifying the full state may not always possible since the storage cost could be huge for some light weight usage such as light client.
```suggestion
Verification is important for trustless decentralised protocol. Verifying the full state may not always be possible since the storage cost could be huge for some light weight usage such as light client. With Merkle Proof, a user 
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +This is a new feature added on top of the existing account management code, and thus has no compatibility concerns.
```suggestion
As this introduces a new data structure, contract state migration will be required.
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +As part of the Zilliqa protocol module, an additional RPC method called `GetProof` should be defined as follows:
```suggestion
As part of the Zilliqa protocol module, an additional RPC method called `GetStateProof` should be defined as follows:
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +### GetProof
```suggestion
### GetStateProof
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +
```suggestion

### Other information

Storing proofs of every TxBlock can take up a significant amount of storage space. As such, the node will only store the latest 50 TxBlock proof. This value can be adjusted in future upgrades. 
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +Assuming a contract at block 981000 has following status and states:
```suggestion
Assuming a contract at block 981000 has following states:
```

2022-02-04 03:53 UTC, bb111189 commented on zips/zip-16.md
> +With Merkle Tree we are allowed to verify all the account state data in Zilliqa. But in order to verify accounts offline, we need a feature to provide proof which is important for the security of Lay
```suggestion
With Merkle Patricia Tree we are allowed to verify all the account state data in Zilliqa. But in order to verify accounts offline, we need a feature to provide proof which is important for the security of Layer 2 services and cross-chain bridges.
```

2022-02-04 05:49 UTC, bb111189 approved these changes

2022-02-04 05:49 UTC, merged