[ZIP19] Seed Node Staking Mechanism: Phase I.1
Zilliqa/ZIP pull request #60
Opened 2021-03-26 03:26 UTC by bb111189

2021-05-04 10:18 UTC, AmritKumar commented on zips/README.md
> +| 19 | Seed Node Staking Mechanism: Phase I.1     |
```suggestion
| 19 | Seed Node Staking Mechanism: Phase 1.1     |
```

2021-05-04 10:20 UTC, AmritKumar commented on zips/zip-19.md
> +presented in [ZIP-11](https://github.com/Zilliqa/ZIP/blob/master/zips/zip-3.md).
```suggestion
presented in [ZIP-11](https://github.com/Zilliqa/ZIP/blob/master/zips/zip-11.md).
```

2021-05-04 10:20 UTC, AmritKumar commented on zips/zip-19.md
> +This new proposal introduces a new mechanism to transfer stake from one account to another account.
```suggestion
This new proposal introduces a mechanism to transfer stake from one account to another account. 
```

2021-05-04 10:22 UTC, AmritKumar commented on zips/zip-19.md
> +In addition, it also fixes an empty map deletion bug in Phase 1 and resolves compatibility issue with upcoming Scilla version `0.10.0` upgrade.
```suggestion
Additionally, it also fixes a bug related to incorrect deletion of empty maps and resolves compatibility issues with the upcoming Scilla version `0.10.0` upgrade.
```

2021-05-04 10:32 UTC, AmritKumar commented on zips/zip-19.md
> +The Zilliqa team will facilitate the migration of contract states from phase 1 to phase 1.1 via remote state read, which will be part of Zilliqa v8.0.0 release.
```suggestion
The Zilliqa team will facilitate the migration of contract states from Phase 1 to Phase 1.1 via remote state read, which will be part of Zilliqa v8.0.0 release.
```

2021-05-04 10:55 UTC, AmritKumar requested changes

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +The Staking phase 1 has been a success and many Zilliqa wallet providers such as [Atomic](https://atomicwallet.io/staking),
```suggestion
Seed Node Staking (Phase 1) has been a success and many Zilliqa wallet providers such as [Atomic](https://atomicwallet.io/staking), 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +However, the team has received feedback on how to further improve the Zilliqa non-custodial seed node staking program.
```suggestion
However, the team has received some feedback on how to further improve the user experience. This proposal aims to cater to one such feedback.
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +The current staking contracts for phase 1 is not versatile enough to support smart contract wallets. For smart contract wallets,
```suggestion
The current staking contracts for Phase 1 are not versatile enough to support smart contract wallets. For smart contract wallets, 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +if the wallet provider needs to "upgrade" or add new features to the smart contract, a new deployment of the smart contract and followed
```suggestion
if the wallet provider needs to "upgrade" or add new features to the smart contract, a new deployment of the smart contract, followed 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +by a transfer of assets to the new smart contract is required. Under Staking phase 1, this means that the delegator has to withdraw all his stakes,
```suggestion
by a transfer of assets to the new smart contract is required. With Staking Phase 1, this means that the delegator has to withdraw all his stakes, 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +Maps entries that are not required are deleted from the contract state. However, due to an improper deletion in phase 1, rather than map entries being deleted,
```suggestion
Maps entries that are not required are deleted from the contract state. However, due to an incomplete deletion in Phase 1, rather than map entries being deleted, 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +the map entries are cleared instead. This causes the contract data size to be bloated unnecessary.
```suggestion
the map entries are cleared instead. This causes the contract data size to be get unnecessarily bloated.
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +there is no restriction on the number of transfers.
```suggestion
there will be no restriction on the number of transfers.
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +### Scenario 2: Transferring to an address which currently have 1 or more stake delegation or pending stake withdrawal
```suggestion
### Scenario 2: Transferring to an address which currently has 1 or more stake delegation or pending stake withdrawal
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +All stake deposits and rewards will be transferred ot the new address. If there is any overlap with the existing stake delegation, rewartds or pending withdrawal, the
```suggestion
All stake deposits and rewards will be transferred to the new address. If there is any overlap with the existing stake delegation, rewards or pending withdrawal, the
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +B accepts A request; B inherit all of A's stake
```suggestion
B accepts A's request; B inherits all of A's stake
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +A accepts B request; A inherit all of B's stake
```suggestion
A accepts B's request; A inherits all of B's stake
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +Next, B accepts A request; B is the final inheritor
```suggestion
Next, B accepts A's request; B is the final inheritor
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +However, there is no identified use case for cyclic transfer of a stake. Additionally, it may impact overall user experience. As such, such cyclic transfer will be disabled i.e If the recipient is al
```suggestion
However, there is no identified use case for cyclic transfer of a stake. Additionally, it may impact overall user experience. As such, such cyclic transfer will be disabled i.e., if the recipient is already a requestor in the `deleg_swap_request` map, transfer of stake request will not be possible till acceptance or cancellation of request. However, non-cyclic transfer will still be possible even if there is a pending stake transfer. 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +The transfer will adopt a two step process. First the transferer will need to initiate a request to transfer to another address. The recipient will then need to
```suggestion
The transfer will adopt a two-step process. First the transferer will need to initiate a request to transfer to another address. The recipient will then need to 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +| RequestDelegatorSwap | To initiate the request to transfer all existing stake deposit, rewards and pending withdrawals |
```suggestion
| `RequestDelegatorSwap` | To initiate the request to transfer all existing stake deposit, rewards and pending withdrawals |
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +| ConfirmDelegatorSwap | To execute the transfer |
```suggestion
| `ConfirmDelegatorSwap` | To execute the transfer |
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +| RevokeDelegatorSwap | To cancel the transfer by the requestor |
```suggestion
| `RevokeDelegatorSwap` | To cancel the transfer by the requestor |
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +| RejectDelegatorSwap | To cancel the transfer request from a specific requestor |
```suggestion
| `RejectDelegatorSwap` | To cancel the transfer request from a specific requestor |
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +We have also implemented the following transition. tt will be used by the contract admin to clean up any empty map post state migration.
```suggestion
We have also implemented the following transitions. They  will be used by the contract admin to clean up any empty map post state migration. 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanBuffDeposit
```suggestion
- `CleanBuffDeposit`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanDirectDeposit
```suggestion
- `CleanDirectDeposit`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanDelegStakePerCycle
```suggestion
- `CleanDelegStakePerCycle`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanDepositAmt
```suggestion
- `CleanDepositAmt`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanPendingWithdrawal
```suggestion
- `CleanPendingWithdrawal`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanLastWithdrawCycle
```suggestion
- `CleanLastWithdrawCycle`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- CleanLastBuffDepositCycle
```suggestion
- `CleanLastBuffDepositCycle`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +A new set of smart contracts will be deployed and populated with the states from the phase 1 staking contracts. Both remote state read and populate transition will be used to populate the phase 1.1 s
```suggestion
A new set of smart contracts will be deployed and populated with the states from the Phase 1 staking contracts. Both remote state read and populate transitions will be used to populate the Phase 1.1 staking contracts. 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +For maps with no user defined ADTs, remote state read will be used to read the states from the phase 1 contract and populate it into the phase 1.1 contract. The following map will
```suggestion
For maps with no user defined ADTs, remote state read will be used to read the states from the Phase 1 contract and populate it into the Phase 1.1 contract. The following maps will
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- comm_for_ssn
```suggestion
- `comm_for_ssn`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- deposit_amt_deleg
```suggestion
- `deposit_amt_deleg`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- ssn_deleg_amt
```suggestion
- `ssn_deleg_amt`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- buff_deposit_deleg
```suggestion
- `buff_deposit_deleg`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- direct_deposit_deleg
```suggestion
- `direct_deposit_deleg`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- last_withdraw_cycle_deleg
```suggestion
- `last_withdraw_cycle_deleg`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- last_buf_deposit_cycle_deleg
```suggestion
- `last_buf_deposit_cycle_deleg`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- deleg_stake_per_cycle
```suggestion
- `deleg_stake_per_cycle`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +- withdrawal_pending
```suggestion
- `withdrawal_pending`
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +ZIP-19 aims to make minor functional improvements and fixes to the non custodial staking contract.
```suggestion
ZIP-19 aims to make minor functional improvements and fixes to the non-custodial staking contract. 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +* The specification for the different contracts needed for Phase 1.1 can be found in the [readme](https://github.com/Zilliqa/staking-contract/blob/main/README.md)
```suggestion
* The specification for the different contracts needed for Phase 1.1 can be found in the [Readme](https://github.com/Zilliqa/staking-contract/blob/main/README.md)
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +As phase 1 contract states contain nested maps with empty entries, `clean*` transition will be used after the population to clean up any empty maps.
```suggestion
As Phase 1 contract states contain nested maps with empty entries, `clean*` transitions will be used after the population to clean up any empty maps. 
```

2021-05-04 10:55 UTC, AmritKumar commented on zips/zip-19.md
> +For the remaining of the maps,p the `populate*` transitions will be use to manually populate each map.
```suggestion
For the remaining of the maps, the `populate*` transitions will be use to manually populate each map. 
```

2021-05-04 18:00 UTC, AmritKumar approved these changes

2021-05-05 02:49 UTC, teye approved these changes

2021-05-05 03:18 UTC, renlulu approved these changes

2021-05-05 03:43 UTC, merged