Zip-20: Adjust staking bonding period
Zilliqa/ZIP pull request #66
Opened 2021-06-15 06:17 UTC by bb111189

This proposal adjust the bonding period. This proposal will need to undergo governance voting

2021-06-15 06:54 UTC, AmritKumar commented on zips/zip-20.md
> +Since Staking phase 1.0 launched, the bonding period has set to ~2 weeks. Since then, there have been discussions on adjusting the bonding period
```suggestion
Since Staking phase 1.0 launched, the bonding period has been set to ~2 weeks. Since then, there have been discussions on adjusting the bonding period
```

2021-06-15 06:55 UTC, AmritKumar commented on zips/zip-20.md
> +of Zilliqa staking phase 1.0/1.1. A recent straw poll with 98 voters (as of the writing of this ZIP) on [Zilliqa governance forum](https://gov.zilliqa.com/t/reduce-the-unstaking-period/568/13?u=junha
```suggestion
of Zilliqa staking phase 1.0/1.1. A recent straw poll with 98 voters (as of writing of this ZIP) on [Zilliqa governance forum](https://gov.zilliqa.com/t/reduce-the-unstaking-period/568/13?u=junhaotan) indicated that many will like to reduce the bonding period to a period of ~1 week.
```

2021-06-15 06:56 UTC, AmritKumar commented on zips/zip-20.md
> +  * [Bonding period comparsion](#bonding-period-comparsion)
```suggestion
  * [Bonding period comparison](#bonding-period-comparison)
```

2021-06-15 06:56 UTC, AmritKumar commented on zips/zip-20.md
> +## Bonding period comparsion
```suggestion
## Bonding period comparison
```

2021-06-15 06:57 UTC, AmritKumar requested changes
Some typo fixes needed.

2021-06-15 08:59 UTC, renlulu approved these changes

2021-06-16 01:59 UTC, teye approved these changes

2023-12-18 15:58 UTC, rrw-zilliqa commented
This PR has been lurking for 2y and AFAICT the governance proposal never happened - if anyone still wants to do this, please get in touch and we'll do a governance vote, but in the meantime, closing.

2023-12-18 15:58 UTC, closed without merging