(feat) A ZIP for reward control.
Zilliqa/ZIP pull request #71
Opened 2023-10-17 08:54 UTC by rrw-zilliqa

What the title says.

2023-10-17 09:40 UTC, DrZoltanFazekas requested changes
just 2 minor things, see comments

2023-10-17 09:40 UTC, DrZoltanFazekas commented on zips/zip-24.md
> +Governance proposal GP008 was passed on 2023-10-14 to address thisw,
typo in line 19: `thisw`

2023-10-17 09:40 UTC, DrZoltanFazekas commented on zips/zip-24.md
> +<REWARD_CONTROL_CONTRACT_ADDRESS>(address)</REWARD_CONTROL_CONTRACT_ADDRESS></transactions>.
line 32: formatting broken

2023-11-28 15:33 UTC, JamesHinshelwood approved these changes

2023-11-28 15:43 UTC, DrZoltanFazekas approved these changes

2023-11-28 15:43 UTC, merged